language: rust
cache: cargo
script:
  - cargo build --verbose --release --target x86_64-unknown-linux-musl
  - cargo test --verbose --target x86_64-unknown-linux-musl
before_deploy:
  - mkdir deployment
  - mv ./target/x86_64-unknown-linux-musl/release/bootstrap ./deployment/bootstrap
  - cd deployment
  - zip rust-lambda-cd bootstrap
  - rm bootstrap
  - cd ..
deploy:
  skip_cleanup: true
  provider: s3
  bucket: $S3_BUCKET
  upload-dir: $S3_UPLOAD_DIR
  local_dir: "deployment"
  region: $AWS_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY