language: generic
sudo: required
install: docker pull clux/muslrust
script: docker run -v $PWD:/volume --rm -t clux/muslrust cargo build --release --verbose
before_deploy:
  - mkdir deployment
  - sudo chown $USER ./target/x86_64-unknown-linux-musl/release/bootstrap
  - sudo mv ./target/x86_64-unknown-linux-musl/release/bootstrap ./deployment/bootstrap
  - cd deployment
  - sudo zip rust-lambda-cd bootstrap
  - sudo rm bootstrap
  - cd ..
deploy:
  skip_cleanup: true
  provider: s3
  bucket: $S3_BUCKET
  upload-dir: $S3_UPLOAD_DIR
  local_dir: "deployment"
  region: $AWS_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY